version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: title
        must_exclude:
          regex: 'WIP'
      - do: label
        must_exclude:
          regex: 'WIP'
      - do: description
        no_empty:
          enabled: true
          message: Descriptions should not be empty. Provide detail with **what** was changed, **why** it was changed, and **how** it was changed.
      - do: dependent
        changed:
          file: package.json
          files: ['yarn.lock']
          message: >
            The lock files for Yarn must be updated when updating the package manifest.
      - do: dependent
        changed:
          file: Gemfile
          files: ['Gemfile.lock']
          messsage: >
            The Bundler lock file must be updated when updating the Gemfile to ensure that it remains valid.
