require: 
  - rubocop-rspec
  - rubocop-performance

inherit_mode:
  merge:
    - Include
    - Exclude

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - 'lib/'
  Exclude:
    - 'db/**/*'
    - 'bin/bundle'

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  ExcludedMethods:
    - 'describe'
    - 'context'
    - 'concern'
    - 'concerning'
    - 'class_methods'
    - 'included'
    - 'state_machine'

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 250

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 250

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - 'id'
    - 'ip'

Naming/UncommunicativeBlockParamName:
  AllowedNames:
    - 'id'
    - 'ip'

Performance/RedundantMerge:
  MaxKeyValuePairs: 1

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation

Rails/ApplicationRecord:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/UnknownEnv:
  Environments: [ production, staging, development, test, asset_precompile ]

Style/EmptyMethod:
  EnforcedStyle: expanded

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2

Style/MutableConstant:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

CaseIndentation:
  EnforcedStyle: end

Style/SpecialGlobalVars:
  Enabled: false

RSpec/ExampleLength:
  Max: 10
